Repository kavindyasinthasilva/hacktoberfest-2020, pull requests merged in 2020-10, with the labels that each got.

#7 Added my files, first PR
  image/juuz0.jpg
  juuz0.md
Labels: HACKTOBERFEST

#10 Added my slogans and image
  image/omkumar40.jpg
  omkumar40.md
Labels: HACKTOBERFEST

#9 open source
  image/reethik.jpg
  reethik.md
Labels: HACKTOBERFEST

#12 Add my personal information
  image/ctahirih.jpg
  tahirih.md
Labels: HACKTOBERFEST

#11 Added climate change image
  image/muskan_rani.jpg
  muskan_rani.md
Labels: HACKTOBERFEST

#14 Create resmitha.md
  resmitha.md
Labels: HACKTOBERFEST

#15 Create resmithaa.md
  resmithaa.md
Labels: hacktoberfest-accepted

#16 Update Hackto.md
  Hackocta.md
Labels: hacktoberfest-accepted

#17 harbajan.md
  muskan_rani.md
Labels: hacktoberfest-accepted

#20 Akila
  Akila
Labels: hacktoberfest-accepted

#21 Update edit.css
  edit.css
Labels: HACKTOBERFEST, hacktoberfest-accepted

#19 changes
  change.md
  tahirih.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#18 change
  omkumar40.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#22 Update Akila
  Akila
Labels: HACKTOBERFEST, hacktoberfest-accepted

#23 Update edit.html
  edit.html
Labels: HACKTOBERFEST, hacktoberfest-accepted

#24 Update edit.html
  edit.html
Labels: HACKTOBERFEST, hacktoberfest-accepted

#25 changes
  tanut2539.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#26 Create hackocta
  hackocta
Labels: HACKTOBERFEST, hacktoberfest-accepted

#27 Update hackocta
  hackocta
Labels: HACKTOBERFEST, hacktoberfest-accepted

#29 Update change.md
  change.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#28 Update hackocta
  hackocta
Labels: HACKTOBERFEST, hacktoberfest-accepted

#32 added image and md file for me
  aimee.md
  image/aimee.jpg
Labels: HACKTOBERFEST, hacktoberfest-accepted

#33 Review window time has changed now
  README.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#35 Create Vihanga
  Vihanga
Labels: HACKTOBERFEST, hacktoberfest-accepted

#38 Create M1STAK3
  M1STAK3
Labels: HACKTOBERFEST, hacktoberfest-accepted

#37 Create octa
  octa
Labels: HACKTOBERFEST, hacktoberfest-accepted

#36 Create Vihanga(1)
  Vihanga(1)
Labels: HACKTOBERFEST, hacktoberfest-accepted

#39 Added new text document
  Htbrfest.txt
Labels: HACKTOBERFEST, hacktoberfest-accepted

#40 new file added
  image/the-wrong-guy.jpeg
  the-wrong-guy.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#41 Create patrick.md
  patrick.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#42 Update patrick.md
  patrick.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#43 added message and image
  eddie.md
  image/eddie.jpg
Labels: HACKTOBERFEST, hacktoberfest-accepted

#44 Added rs.html file
  rs.html
Labels: HACKTOBERFEST, hacktoberfest-accepted

#45 Added final.txt
  final.txt
Labels: HACKTOBERFEST, hacktoberfest-accepted

#47 added myself
  image/skipboredom.jpg
  skipboredom.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#46 Adding new user and change
  image/soyvikman.jpg
  soyvikman.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#48 added Array question
  Array/Question
  Array/answer.c
Labels: HACKTOBERFEST, hacktoberfest-accepted

#49 hacktoberfest-accepted
  image/katherine.jpg
  katherine.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#52 Save Earth
  arpitkushwaha.md
  image/arpitkushwaha.jpg
Labels: HACKTOBERFEST, hacktoberfest-accepted

#53 Create name.md
  name.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#51 My Contribution to Hacktoberfest 2020
  a.md
Labels: HACKTOBERFEST, hacktoberfest-accepted

#54 Create dev
  dev
Labels: HACKTOBERFEST, hacktoberfest-accepted

#50 Add files via upload
  Whtsapp autmation.js
Labels: HACKTOBERFEST, hacktoberfest-accepted

#55 Create Abey123
  Abey123
Labels: HACKTOBERFEST, hacktoberfest-accepted

#56 Create Cony
  Cony
Labels: HACKTOBERFEST, hacktoberfest-accepted

#57 Added SignIn.html
  SignIn.html
  convert.c
Labels: HACKTOBERFEST, hacktoberfest-accepted

#58 Create doc
  doc
Labels: HACKTOBERFEST, hacktoberfest-accepted

#60 Create Onez
  Onez
Labels: HACKTOBERFEST, hacktoberfest-accepted

#59 Create git
  git
Labels: HACKTOBERFEST, hacktoberfest-accepted

#62 Create Hacktomber1
  Hacktomber1
Labels: HACKTOBERFEST, hacktoberfest-accepted

#61 Create hacktober
  hacktober
Labels: HACKTOBERFEST, hacktoberfest-accepted

#65 recursive function
  recursive.c
Labels: HACKTOBERFEST, hacktoberfest-accepted

#64 Create Hacktoberfest3
  Hacktoberfest3
Labels: HACKTOBERFEST, hacktoberfest-accepted

#63 Create Hacktomberfest2
  Hacktomberfest2
Labels: HACKTOBERFEST, hacktoberfest-accepted

#66 Image added
  .DS_Store
  hackfest.md
  image/hacktoberfest.jpg
Labels: HACKTOBERFEST, hacktoberfest-accepted

#67 Add new image and MD file
  image/sergio_yonashiro.jpg
  sergio_yonashiro.md
Labels: HACKTOBERFEST, hacktoberfest-accepted
